import { Product, Category } from '@/types/database';

const now = new Date().toISOString();

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Cars', slug: 'cars', icon: 'car', description: 'Buy and sell pre-owned cars', is_active: true, sort_order: 1, created_at: now },
  { id: '2', name: 'Mobiles', slug: 'mobiles', icon: 'smartphone', description: 'Phones, tablets and accessories', is_active: true, sort_order: 2, created_at: now },
  { id: '3', name: 'Bikes', slug: 'bikes', icon: 'wrench', description: 'Motorcycles and scooters', is_active: true, sort_order: 3, created_at: now },
  { id: '4', name: 'Electronics', slug: 'electronics', icon: 'smartphone', description: 'TVs, Laptops, and more', is_active: true, sort_order: 4, created_at: now },
  { id: '5', name: 'Furniture', slug: 'furniture', icon: 'sofa', description: 'Home decor and furniture', is_active: true, sort_order: 5, created_at: now },
  { id: '6', name: 'Properties', slug: 'properties', icon: 'home', description: 'Houses, flats and land', is_active: true, sort_order: 6, created_at: now },
  { id: '7', name: 'Jobs', slug: 'jobs', icon: 'briefcase', description: 'Find your next career move', is_active: true, sort_order: 7, created_at: now },
  { id: '8', name: 'Pets', slug: 'pets', icon: 'dog', description: 'Dogs, cats and birds', is_active: true, sort_order: 8, created_at: now },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'm1',
    user_id: 'u1',
    category_id: '2',
    title: 'Samsung Galaxy S24 Ultra - 512GB (Titanium Gray)',
    description: 'Perfect condition Galaxy S24 Ultra. Used for only 1 month. Includes original box, bill, and all accessories. No scratches, protected by tempered glass since day one.',
    price: 92000,
    currency: 'INR',
    condition: 'like_new',
    images: ['https://images.unsplash.com/photo-1707255139049-923f1244d03d?auto=format&fit=crop&q=80&w=800'],
    location: 'Bandra, Mumbai',
    is_negotiable: true,
    status: 'active',
    views_count: 1240,
    is_featured: true,
    tier: 'premium',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'm2',
    user_id: 'u2',
    category_id: '1',
    title: 'BMW 3 Series 330i M Sport - 2022 Model',
    description: 'Single owner, only 8,500 kms driven. Under warranty and insurance. Pure white with tan leather interior. Showroom condition.',
    price: 4850000,
    currency: 'INR',
    condition: 'like_new',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800'],
    location: 'Gurugram, HR',
    is_negotiable: false,
    status: 'active',
    views_count: 5420,
    is_featured: true,
    tier: 'premium',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm3',
    user_id: 'u3',
    category_id: '2',
    title: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    description: 'Battery health 100%. Comes with Apple Care+ till 2025. Unmatched performance and camera quality.',
    price: 115000,
    currency: 'INR',
    condition: 'like_new',
    images: ['https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&q=80&w=800'],
    location: 'Indiranagar, Bengaluru',
    is_negotiable: true,
    status: 'active',
    views_count: 890,
    is_featured: false,
    tier: 'standard',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm4',
    user_id: 'u4',
    category_id: '6',
    title: 'Luxury 3BHK Apartment - Sea View - High Floor',
    description: 'Spacious 2400 sq.ft 3BHK with modern amenities. Gym, Swimming pool, and 24/7 security. Prime location.',
    price: 32500000,
    currency: 'INR',
    condition: 'new',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800'],
    location: 'Worli, Mumbai',
    is_negotiable: true,
    status: 'active',
    views_count: 15600,
    is_featured: true,
    tier: 'premium',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm5',
    user_id: 'u5',
    category_id: '3',
    title: 'Royal Enfield Interceptor 650 (Baker Express)',
    description: '2021 model, sparingly used. Aftermarket exhaust and touring seat added. Perfect for long rides.',
    price: 245000,
    currency: 'INR',
    condition: 'good',
    images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&q=80&w=800'],
    location: 'Pune, Maharashtra',
    is_negotiable: true,
    status: 'active',
    views_count: 450,
    is_featured: false,
    tier: 'standard',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm6',
    user_id: 'u6',
    category_id: '4',
    title: 'Sony PlayStation 5 Disc Edition with 2 Controllers',
    description: 'Includes God of War and Spider-Man 2 games. 6 months warranty remaining. Extremely well maintained.',
    price: 42000,
    currency: 'INR',
    condition: 'like_new',
    images: ['https://images.unsplash.com/photo-1606813907291-d86ebb9c74ad?auto=format&fit=crop&q=80&w=800'],
    location: 'South Delhi, DL',
    is_negotiable: false,
    status: 'active',
    views_count: 310,
    is_featured: false,
    tier: 'free',
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm7',
    user_id: 'u7',
    category_id: '4',
    title: 'MacBook Pro 14" M3 Pro Chip - 18GB/512GB',
    description: 'Space Black. Seal pack, international warranty. The most powerful laptop for creators.',
    price: 185000,
    currency: 'INR',
    condition: 'new',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800'],
    location: 'Hyderabad, TS',
    is_negotiable: false,
    status: 'active',
    views_count: 2100,
    is_featured: true,
    tier: 'premium',
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm8',
    user_id: 'u8',
    category_id: '5',
    title: 'Modern L-Shaped Sofa Set - Pure Leather',
    description: '5 seater beige leather sofa. Extremely comfortable. No tears or stains. Bought for 1.2 Lakh last year.',
    price: 45000,
    currency: 'INR',
    condition: 'good',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800'],
    location: 'Salt Lake, Kolkata',
    is_negotiable: true,
    status: 'active',
    views_count: 180,
    is_featured: false,
    tier: 'standard',
    created_at: new Date(Date.now() - 432000000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm9',
    user_id: 'u9',
    category_id: '1',
    title: 'Honda City ZX CVT - 2021 Model',
    description: 'Sunroof, automatic transmission, pearl white. All service records available from authorised dealer.',
    price: 1250000,
    currency: 'INR',
    condition: 'good',
    images: ['https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80&w=800'],
    location: 'Chennai, TN',
    is_negotiable: true,
    status: 'active',
    views_count: 670,
    is_featured: false,
    tier: 'free',
    created_at: new Date(Date.now() - 518400000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm10',
    user_id: 'u10',
    category_id: '4',
    title: 'Dyson Airwrap Multistyler (Complete Long)',
    description: 'All attachments included. Original luxury case and cleaning brush. Perfect for hair styling at home.',
    price: 32000,
    currency: 'INR',
    condition: 'like_new',
    images: ['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&q=80&w=800'],
    location: 'Ahmedabad, GJ',
    is_negotiable: false,
    status: 'active',
    views_count: 890,
    is_featured: true,
    tier: 'premium',
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: now,
  },
  {
    id: 'm11',
    user_id: 'u11',
    category_id: '4',
    title: 'Vintage Rolex Submariner Date - 2015',
    description: 'Original box and papers. Certified authentic. A timeless investment piece.',
    price: 950000,
    currency: 'INR',
    condition: 'good',
    images: ['https://images.unsplash.com/photo-1547996160-81dfa63595dd?auto=format&fit=crop&q=80&w=800'],
    location: 'South Mumbai, MH',
    is_negotiable: false,
    status: 'active',
    views_count: 12400,
    is_featured: true,
    tier: 'premium',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'm12',
    user_id: 'u12',
    category_id: '2',
    title: 'Google Pixel 8 Pro - 128GB (Bay Blue)',
    description: 'Mint condition. Incredible AI cameras and smooth Android experience. Clean and minimal.',
    price: 78000,
    currency: 'INR',
    condition: 'like_new',
    images: ['https://images.unsplash.com/photo-1696081442749-8ba615174092?auto=format&fit=crop&q=80&w=800'],
    location: 'Whitefield, Bengaluru',
    is_negotiable: true,
    status: 'active',
    views_count: 540,
    is_featured: false,
    tier: 'standard',
    created_at: now,
    updated_at: now,
  }
];
