import { Product, Category, Profile } from '@/types/database';

const now = new Date().toISOString();

export const MOCK_USERS: Profile[] = [
  {
    id: 'mock-user-1',
    full_name: 'Rahul Kapoor',
    avatar_url: 'https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg',
    phone: '+91 9876543210',
    location: 'Mumbai, Maharashtra',
    bio: 'Premium seller on SellAdv.com. Selling verified and quality products.',
    is_admin: false,
    rating: 4.9,
    total_reviews: 42,
    active_listings_count: 24,
    favorites_count: 5,
    views_count: 15400,
    is_verified: true,
    created_at: now,
    updated_at: now,
  }
];

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Cars', slug: 'cars', icon: 'car', description: 'Buy and sell pre-owned cars', is_active: true, sort_order: 1, created_at: now },
  { id: '2', name: 'Mobiles', slug: 'mobiles', icon: 'smartphone', description: 'Phones, tablets and accessories', is_active: true, sort_order: 2, created_at: now },
  { id: '3', name: 'Bikes', slug: 'bikes', icon: 'wrench', description: 'Motorcycles and scooters', is_active: true, sort_order: 3, created_at: now },
  { id: '4', name: 'Electronics', slug: 'electronics', icon: 'monitor', description: 'TVs, Laptops, and more', is_active: true, sort_order: 4, created_at: now },
  { id: '5', name: 'Furniture', slug: 'furniture', icon: 'sofa', description: 'Home decor and furniture', is_active: true, sort_order: 5, created_at: now },
  { id: '6', name: 'Properties', slug: 'properties', icon: 'home', description: 'Rent, sell houses, flats and land', is_active: true, sort_order: 6, created_at: now },
  { id: '7', name: 'Jobs', slug: 'jobs', icon: 'briefcase', description: 'Find your next career move', is_active: true, sort_order: 7, created_at: now },
  { id: '8', name: 'Pets', slug: 'pets', icon: 'bug', description: 'Dogs, cats and birds', is_active: true, sort_order: 8, created_at: now },
  { id: '9', name: 'Fashion', slug: 'fashion', icon: 'shirt', description: 'Clothes, shoes and accessories', is_active: true, sort_order: 9, created_at: now },
  { id: '10', name: 'Services', slug: 'services', icon: 'tool', description: 'Plumbers, electricians, tutors', is_active: true, sort_order: 10, created_at: now },
];

export const MOCK_PRODUCTS: Product[] = [
  // --- PROPERTIES (Category 6) ---
  {
    id: 'p1', user_id: 'mock-user-1', category_id: '6',
    title: 'Luxury 3BHK Apartment - Sea View For Rent',
    description: 'Spacious 2400 sq.ft 3BHK with modern amenities. Gym, Swimming pool. Perfect for families looking to rent in a prime location in Mumbai.',
    price: 85000, currency: 'INR', condition: 'like_new',
    images: [`https://picsum.photos/seed/4879/800/600`],
    location: 'Worli, Mumbai', is_negotiable: true, status: 'active',
    views_count: 1560, is_featured: true, tier: 'premium',
    created_at: new Date(Date.now() - 86400000).toISOString(), updated_at: now,
  },
  {
    id: 'p2', user_id: 'mock-user-1', category_id: '6',
    title: 'Independent Villa For Sale',
    description: '4 Bedroom independent villa with private garden and 2 car parking spots.',
    price: 45000000, currency: 'INR', condition: 'new',
    images: [`https://picsum.photos/seed/6659/800/600`],
    location: 'Whitefield, Bengaluru', is_negotiable: true, status: 'active',
    views_count: 1200, is_featured: false, tier: 'premium',
    created_at: new Date(Date.now() - 186400000).toISOString(), updated_at: now,
  },
  {
    id: 'p3', user_id: 'mock-user-1', category_id: '6',
    title: 'Cozy 1BHK Flat for Rent',
    description: 'Perfect for bachelors or young couples. Fully furnished, near metro station.',
    price: 25000, currency: 'INR', condition: 'good',
    images: [`https://picsum.photos/seed/2892/800/600`],
    location: 'Koramangala, Bengaluru', is_negotiable: false, status: 'active',
    views_count: 500, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 36400000).toISOString(), updated_at: now,
  },
  {
    id: 'p4', user_id: 'mock-user-1', category_id: '6',
    title: 'Commercial Office Space - 5000 sqft',
    description: 'Prime commercial location, high-speed elevators, 100% power backup.',
    price: 350000, currency: 'INR', condition: 'new',
    images: [`https://picsum.photos/seed/6163/800/600`],
    location: 'Cyber City, Gurugram', is_negotiable: true, status: 'active',
    views_count: 750, is_featured: true, tier: 'premium',
    created_at: new Date(Date.now() - 286400000).toISOString(), updated_at: now,
  },
  {
    id: 'p5', user_id: 'mock-user-1', category_id: '6',
    title: 'Studio Apartment for Rent',
    description: 'Fully functional studio, perfect for working professionals.',
    price: 18000, currency: 'INR', condition: 'good',
    images: [`https://picsum.photos/seed/7567/800/600`],
    location: 'HSR Layout, Bengaluru', is_negotiable: false, status: 'active',
    views_count: 420, is_featured: false, tier: 'free',
    created_at: now, updated_at: now,
  },

  // --- MOBILES (Category 2) ---
  {
    id: 'm1', user_id: 'mock-user-1', category_id: '2',
    title: 'Samsung Galaxy S24 Ultra - 512GB (Titanium Gray)',
    description: 'Perfect condition Galaxy S24 Ultra. Used for only 1 month. Includes original box, bill, and all accessories.',
    price: 92000, currency: 'INR', condition: 'like_new',
    images: [`https://picsum.photos/seed/7974/800/600`],
    location: 'Bandra, Mumbai', is_negotiable: true, status: 'active',
    views_count: 1240, is_featured: true, tier: 'premium',
    created_at: now, updated_at: now,
  },
  {
    id: 'm2', user_id: 'mock-user-1', category_id: '2',
    title: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    description: 'Battery health 100%. Comes with Apple Care+ till 2025. Unmatched performance and camera quality.',
    price: 115000, currency: 'INR', condition: 'like_new',
    images: [`https://picsum.photos/seed/5524/800/600`],
    location: 'Indiranagar, Bengaluru', is_negotiable: true, status: 'active',
    views_count: 890, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 7200000).toISOString(), updated_at: now,
  },
  {
    id: 'm3', user_id: 'mock-user-1', category_id: '2',
    title: 'Google Pixel 8 Pro - 128GB (Bay Blue)',
    description: 'Mint condition. Incredible AI cameras and smooth Android experience.',
    price: 78000, currency: 'INR', condition: 'like_new',
    images: [`https://picsum.photos/seed/8376/800/600`],
    location: 'Whitefield, Bengaluru', is_negotiable: true, status: 'active',
    views_count: 540, is_featured: false, tier: 'free',
    created_at: now, updated_at: now,
  },
  {
    id: 'm4', user_id: 'mock-user-1', category_id: '2',
    title: 'OnePlus 12 16GB RAM 512GB Storage',
    description: 'Brand new sealed box. Received as a gift, selling because I prefer iOS.',
    price: 68000, currency: 'INR', condition: 'new',
    images: [`https://picsum.photos/seed/7611/800/600`],
    location: 'Viman Nagar, Pune', is_negotiable: false, status: 'active',
    views_count: 220, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 17200000).toISOString(), updated_at: now,
  },
  {
    id: 'm5', user_id: 'mock-user-1', category_id: '2',
    title: 'iPad Pro M2 11-inch (WiFi + Cellular)',
    description: 'Pristine condition, with Apple Pencil 2nd gen. Used for digital art.',
    price: 72000, currency: 'INR', condition: 'like_new',
    images: [`https://picsum.photos/seed/6955/800/600`],
    location: 'South Delhi, Delhi', is_negotiable: true, status: 'active',
    views_count: 610, is_featured: true, tier: 'standard',
    created_at: new Date(Date.now() - 25200000).toISOString(), updated_at: now,
  },
  {
    id: 'm6', user_id: 'mock-user-1', category_id: '2',
    title: 'Nothing Phone (2) - 12/256GB White',
    description: 'Unique design, Glyph interface, smooth software.',
    price: 32000, currency: 'INR', condition: 'good',
    images: [`https://picsum.photos/seed/9500/800/600`],
    location: 'Salt Lake, Kolkata', is_negotiable: false, status: 'active',
    views_count: 450, is_featured: false, tier: 'free',
    created_at: now, updated_at: now,
  },

  // --- CARS (Category 1) ---
  {
    id: 'c1', user_id: 'mock-user-1', category_id: '1',
    title: 'BMW 3 Series 330i M Sport - 2022 Model',
    description: 'Single owner, only 8,500 kms driven. Under warranty and insurance. Showroom condition.',
    price: 4850000, currency: 'INR', condition: 'like_new',
    images: ['https://picsum.photos/seed/1470/800/600'],
    location: 'Gurugram, Haryana', is_negotiable: false, status: 'active',
    views_count: 5420, is_featured: true, tier: 'premium',
    created_at: new Date(Date.now() - 3600000).toISOString(), updated_at: now,
  },
  {
    id: 'c2', user_id: 'mock-user-1', category_id: '1',
    title: 'Hyundai Creta SX(O) Diesel Automatic - 2021',
    description: 'Well maintained, full service history from Hyundai. Panoramic sunroof, ventilated seats.',
    price: 1650000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/4029/800/600'],
    location: 'Andheri West, Mumbai', is_negotiable: true, status: 'active',
    views_count: 3100, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 8600000).toISOString(), updated_at: now,
  },
  {
    id: 'c3', user_id: 'mock-user-1', category_id: '1',
    title: 'Honda City ZX CVT - 2020 (Top End)',
    description: 'I-VTEC engine, automatic transmission, lane watch camera.',
    price: 1125000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/966/800/600'],
    location: 'Anna Nagar, Chennai', is_negotiable: true, status: 'active',
    views_count: 2200, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 15600000).toISOString(), updated_at: now,
  },
  {
    id: 'c4', user_id: 'mock-user-1', category_id: '1',
    title: 'Tata Harrier XZA+ Dark Edition - 2023',
    description: 'Latest model, ADAS features, only 5,000 kms done. Showroom condition.',
    price: 2250000, currency: 'INR', condition: 'new',
    images: ['https://picsum.photos/seed/6400/800/600'],
    location: 'Banjara Hills, Hyderabad', is_negotiable: false, status: 'active',
    views_count: 3500, is_featured: true, tier: 'premium',
    created_at: now, updated_at: now,
  },

  // --- BIKES (Category 3) ---
  {
    id: 'b1', user_id: 'mock-user-1', category_id: '3',
    title: 'Royal Enfield Interceptor 650 (Baker Express)',
    description: '2021 model, sparingly used. Aftermarket exhaust and touring seat added. Perfect for long rides.',
    price: 245000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/5564/800/600'],
    location: 'Pune, Maharashtra', is_negotiable: true, status: 'active',
    views_count: 450, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 172800000).toISOString(), updated_at: now,
  },
  {
    id: 'b2', user_id: 'mock-user-1', category_id: '3',
    title: 'KTM Duke 390 BS6',
    description: 'TFT Display, quickshifter enabled. Serviced last week, new Pirelli tires.',
    price: 210000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/6229/800/600'],
    location: 'JP Nagar, Bengaluru', is_negotiable: true, status: 'active',
    views_count: 670, is_featured: false, tier: 'free',
    created_at: new Date(Date.now() - 472800000).toISOString(), updated_at: now,
  },
  {
    id: 'b3', user_id: 'mock-user-1', category_id: '3',
    title: 'TVS Apache RR 310 - 2022',
    description: 'Race tuned slipper clutch, multiple riding modes. Extremely well maintained.',
    price: 230000, currency: 'INR', condition: 'like_new',
    images: ['https://picsum.photos/seed/9374/800/600'],
    location: 'Ahmedabad, Gujarat', is_negotiable: true, status: 'active',
    views_count: 510, is_featured: true, tier: 'standard',
    created_at: now, updated_at: now,
  },

  // --- ELECTRONICS (Category 4) ---
  {
    id: 'e1', user_id: 'mock-user-1', category_id: '4',
    title: 'Sony PlayStation 5 Disc Edition with 2 Controllers',
    description: 'Includes God of War and Spider-Man 2 games. 6 months warranty remaining.',
    price: 42000, currency: 'INR', condition: 'like_new',
    images: ['https://picsum.photos/seed/7106/800/600'],
    location: 'South Delhi, Delhi', is_negotiable: false, status: 'active',
    views_count: 310, is_featured: false, tier: 'free',
    created_at: new Date(Date.now() - 259200000).toISOString(), updated_at: now,
  },
  {
    id: 'e2', user_id: 'mock-user-1', category_id: '4',
    title: 'MacBook Pro 14" M3 Pro Chip - 18GB/512GB',
    description: 'Space Black. Seal pack, international warranty.',
    price: 185000, currency: 'INR', condition: 'new',
    images: ['https://picsum.photos/seed/5316/800/600'],
    location: 'Hyderabad, Telangana', is_negotiable: false, status: 'active',
    views_count: 2100, is_featured: true, tier: 'premium',
    created_at: new Date(Date.now() - 345600000).toISOString(), updated_at: now,
  },
  {
    id: 'e3', user_id: 'mock-user-1', category_id: '4',
    title: 'Dell XPS 15 - Core i7, 32GB RAM, 1TB SSD',
    description: 'High performance laptop for video editing and programming.',
    price: 125000, currency: 'INR', condition: 'like_new',
    images: ['https://picsum.photos/seed/9881/800/600'],
    location: 'Chandigarh, Punjab', is_negotiable: true, status: 'active',
    views_count: 890, is_featured: false, tier: 'standard',
    created_at: now, updated_at: now,
  },
  {
    id: 'e4', user_id: 'mock-user-1', category_id: '4',
    title: 'Sony WH-1000XM5 Noise Cancelling Headphones',
    description: 'Barely used, 11 months warranty left. Best-in-class noise cancellation.',
    price: 24000, currency: 'INR', condition: 'like_new',
    images: ['https://picsum.photos/seed/5358/800/600'],
    location: 'Jaipur, Rajasthan', is_negotiable: false, status: 'active',
    views_count: 320, is_featured: false, tier: 'free',
    created_at: now, updated_at: now,
  },

  // --- FURNITURE (Category 5) ---
  {
    id: 'f1', user_id: 'mock-user-1', category_id: '5',
    title: 'Modern L-Shaped Sofa Set - Pure Leather',
    description: '5 seater beige leather sofa. Extremely comfortable. No tears or stains.',
    price: 45000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/8006/800/600'],
    location: 'Salt Lake, Kolkata', is_negotiable: true, status: 'active',
    views_count: 180, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 432000000).toISOString(), updated_at: now,
  },
  {
    id: 'f2', user_id: 'mock-user-1', category_id: '5',
    title: 'Teak Wood Dining Table (6 Seater)',
    description: 'Solid teak wood dining table with 6 cushioned chairs. Excellent finish.',
    price: 28000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/1006/800/600'],
    location: 'Vashi, Navi Mumbai', is_negotiable: true, status: 'active',
    views_count: 140, is_featured: false, tier: 'free',
    created_at: new Date(Date.now() - 832000000).toISOString(), updated_at: now,
  },
  {
    id: 'f3', user_id: 'mock-user-1', category_id: '5',
    title: 'King Size Bed with Orthopedic Mattress',
    description: 'Less than a year old, very sturdy build, storage underneath.',
    price: 35000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/9291/800/600'],
    location: 'Gomti Nagar, Lucknow', is_negotiable: true, status: 'active',
    views_count: 210, is_featured: true, tier: 'standard',
    created_at: now, updated_at: now,
  },

  // --- PETS (Category 8) ---
  {
    id: 'pt1', user_id: 'mock-user-1', category_id: '8',
    title: 'Golden Retriever Puppies - KCI Registered',
    description: 'Pure breed, vaccinated and dewormed golden retriever puppies. 45 days old.',
    price: 25000, currency: 'INR', condition: 'new',
    images: ['https://picsum.photos/seed/3908/800/600'],
    location: 'Sector 17, Chandigarh', is_negotiable: false, status: 'active',
    views_count: 4200, is_featured: true, tier: 'premium',
    created_at: new Date(Date.now() - 10000000).toISOString(), updated_at: now,
  },
  {
    id: 'pt2', user_id: 'mock-user-1', category_id: '8',
    title: 'British Shorthair Kittens',
    description: 'Adorable blue British Shorthair kittens, litter trained, ready for new home.',
    price: 35000, currency: 'INR', condition: 'new',
    images: ['https://picsum.photos/seed/2496/800/600'],
    location: 'Pune, Maharashtra', is_negotiable: true, status: 'active',
    views_count: 1500, is_featured: false, tier: 'standard',
    created_at: now, updated_at: now,
  },

  // --- FASHION (Category 9) ---
  {
    id: 'fs1', user_id: 'mock-user-1', category_id: '9',
    title: 'Air Jordan 1 High OG "Chicago" - Size 9 UK',
    description: '100% authentic, bought from SNKRS app. Worn twice, 9/10 condition. With OG box.',
    price: 35000, currency: 'INR', condition: 'like_new',
    images: ['https://picsum.photos/seed/3452/800/600'],
    location: 'Bandra, Mumbai', is_negotiable: true, status: 'active',
    views_count: 890, is_featured: true, tier: 'standard',
    created_at: new Date(Date.now() - 40000000).toISOString(), updated_at: now,
  },
  {
    id: 'fs2', user_id: 'mock-user-1', category_id: '9',
    title: 'Rolex Submariner Date (Pre-owned)',
    description: '2019 model, complete set with box and papers. Immaculate condition.',
    price: 1150000, currency: 'INR', condition: 'good',
    images: ['https://picsum.photos/seed/7813/800/600'],
    location: 'Connaught Place, Delhi', is_negotiable: true, status: 'active',
    views_count: 15000, is_featured: true, tier: 'premium',
    created_at: now, updated_at: now,
  },

  // --- SERVICES (Category 10) ---
  {
    id: 'sv1', user_id: 'mock-user-1', category_id: '10',
    title: 'Professional Photography Setup & Shoot',
    description: 'Offering portrait and product photography sessions. High end equipment and post-processing included.',
    price: 5000, currency: 'INR', condition: 'new',
    images: ['https://picsum.photos/seed/2435/800/600'],
    location: 'Jaipur, Rajasthan', is_negotiable: true, status: 'active',
    views_count: 230, is_featured: false, tier: 'standard',
    created_at: new Date(Date.now() - 90000000).toISOString(), updated_at: now,
  },
  {
    id: 'sv2', user_id: 'mock-user-1', category_id: '10',
    title: 'Expert AC Repair & Servicing',
    description: 'Same day service. Gas filling, deep cleaning, component repair for all brands.',
    price: 499, currency: 'INR', condition: 'new',
    images: ['https://picsum.photos/seed/269/800/600'],
    location: 'Noida, Uttar Pradesh', is_negotiable: false, status: 'active',
    views_count: 4500, is_featured: true, tier: 'premium',
    created_at: new Date(Date.now() - 1000000).toISOString(), updated_at: now,
  },

  // --- JOBS (Category 7) ---
  {
    id: 'j1', user_id: 'mock-user-1', category_id: '7',
    title: 'Senior Frontend Developer (React Native)',
    description: 'Looking for an experienced React Native developer with 4+ years of experience. Remote work available.',
    price: 3500000, currency: 'INR', condition: 'new',
    images: ['https://picsum.photos/seed/6372/800/600'],
    location: 'Remote, India', is_negotiable: false, status: 'active',
    views_count: 850, is_featured: true, tier: 'standard',
    created_at: new Date(Date.now() - 432000000).toISOString(), updated_at: now,
  }
];

export const MOCK_CONVERSATIONS: any[] = [
  {
    id: 'conv_1',
    product_id: 'p1',
    buyer_id: 'u1',
    seller_id: 'mock-user-1',
    last_message: 'Is the price negotiable?',
    last_message_at: new Date(Date.now() - 3600000).toISOString(),
    unread_count: 1,
    products: MOCK_PRODUCTS[0],
    seller: { full_name: 'Rahul Kapoor', avatar_url: 'https://picsum.photos/seed/6885/100/100' },
  },
  {
    id: 'conv_2',
    product_id: 'm1',
    buyer_id: 'u1',
    seller_id: 'mock-user-1',
    last_message: 'Can I see more photos?',
    last_message_at: new Date(Date.now() - 86400000).toISOString(),
    unread_count: 0,
    products: MOCK_PRODUCTS[4],
    seller: { full_name: 'Priya Verma', avatar_url: 'https://picsum.photos/seed/7595/100/100' },
  }
];

export const MOCK_MESSAGES: any[] = [
  {
    id: 'msg_1',
    conversation_id: 'conv_1',
    sender_id: 'mock-user-1',
    content: 'Hi, I am interested in this apartment.',
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'msg_2',
    conversation_id: 'conv_1',
    sender_id: 'mock-user-1',
    content: 'Hello! Yes, it is available for viewing tomorrow.',
    created_at: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 'msg_3',
    conversation_id: 'conv_1',
    sender_id: 'mock-user-1',
    content: 'Is the price negotiable?',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  }
];

export let MOCK_FAVORITES: string[] = ['p1', 'm1', 'e1'];

export const MOCK_REVIEWS: any[] = [
  {
    id: 'rev_1',
    reviewer_id: 'u2',
    reviewee_id: 'mock-user-1',
    product_id: 'p1',
    rating: 5,
    comment: 'Excellent property and very professional seller. Rahul made the entire process smooth.',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    reviewer: { full_name: 'Ankit Sharma', avatar_url: 'https://picsum.photos/seed/ankit/100/100' }
  },
  {
    id: 'rev_2',
    reviewer_id: 'u3',
    reviewee_id: 'mock-user-1',
    product_id: 'm1',
    rating: 4,
    comment: 'Great phone, exactly as described. Rahul was responsive and helpful.',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    reviewer: { full_name: 'Sneha Reddy', avatar_url: 'https://picsum.photos/seed/sneha/100/100' }
  }
];
